apiVersion: apps/v1
kind: Deployment
metadata:
  name: buksapp-frontend
  labels:
    app: buksapp-frontend
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: buksapp-frontend
      
  template:
    metadata:
      labels:
        app: buksapp-frontend
        tier: buksapp-frontend
    spec:
      containers:
        - name: buksapp-frontend
          image: bukunmi00/buksapp-frontend:tagversion
          imagePullPolicy: Always
          ports:
          - containerPort: 4000
            name: buksapp-frontend


---
apiVersion: v1
kind: Service
metadata:
  name: buksapp-frontend
  labels:
    app: buksapp-frontend
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: buksapp-frontend
    tier: buksapp-frontend
  type: LoadBalancer